import type { IconType } from 'react-icons';
import {
  SiNodedotjs, SiExpress, SiPostgresql, SiTypescript, SiJavascript,
  SiPython, SiSpringboot, SiMysql, SiVuedotjs, SiFlutter, SiDart,
  SiRabbitmq, SiApachenifi, SiPostman, SiNestjs, SiPrisma,
  SiCloudflareworkers, SiCss, SiHtml5, SiNpm, SiAxios,
  SiDiscord, SiDiscorddotjs, SiJunit5,
} from 'react-icons/si';
import {
  FaJava, FaCogs, FaDatabase, FaKey, FaLock, FaFileCode,
  FaTerminal, FaClock, FaFont, FaPaintBrush,
  FaFileAlt, FaPlug, FaRobot, FaServer, FaShieldAlt,
  FaCode, FaFileSignature, FaNetworkWired,
} from 'react-icons/fa';

const TECH_ICON_MAP: Record<string, IconType> = {
  'Node.js':             SiNodedotjs,
  'Express':             SiExpress,
  'PostgreSQL':          SiPostgresql,
  'TypeScript':          SiTypescript,
  'JavaScript':          SiJavascript,
  'Python':              SiPython,
  'Spring Boot':         SiSpringboot,
  'Java':                FaJava,
  'MySQL':               SiMysql,
  'Vue.js':              SiVuedotjs,
  'Flutter':             SiFlutter,
  'Dart':                SiDart,
  'RabbitMQ':            SiRabbitmq,
  'Apache NiFi':         SiApachenifi,
  'Oracle DB':           FaDatabase,
  'Oracle AQ':           FaDatabase,
  'Postman':             SiPostman,
  'NestJS':              SiNestjs,
  'Prisma':              SiPrisma,
  'Cloudflare Workers':  SiCloudflareworkers,
  'CSS':                 SiCss,
  'HTML':                SiHtml5,
  'npm':                 SiNpm,
  'axios':               SiAxios,
  'Helmet':              FaShieldAlt,
  'discord.js':          SiDiscorddotjs,
  'discord-interactions': SiDiscord,
  'Discord Webhook':     SiDiscord,
  'JUnit 5':             SiJunit5,
  'SQL':                 FaDatabase,
  'Robocorp':            FaRobot,
  'SFTP':                FaServer,
  'HSM':                 FaKey,
  'Argon2':              FaLock,
  'SlipOK API':          FaPlug,
  'XAdES':               FaFileSignature,
  'PAdES':               FaFileSignature,
  'PDF/A-3U':            FaFileAlt,
  'JasperReports':       FaFileCode,
  'Mockito':             FaCogs,
  'dotenv':              FaCogs,
  'chalk':               FaPaintBrush,
  'figlet':              FaFont,
  'node-cron':           FaClock,
  'nodemon':             FaTerminal,
  'tsc':                 SiTypescript,
  'tsx':                 SiTypescript,
  'itty-router':         FaNetworkWired,
  'wrangler':            SiCloudflareworkers,
  'otplib':              FaShieldAlt,
  'promptpay-qr':        FaCode,
};

export function getTechIcon(techName: string): IconType | null {
  return TECH_ICON_MAP[techName] ?? null;
}
